# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
 
target 'mobile_game_2048 iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 
  # Pods for mobile_game_2048 iOS
  pod 'Google-Mobile-Ads-SDK'
 
end
 
target 'mobile_game_2048 macOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 
  # Pods for mobile_game_2048 macOS
 
end
 
target 'mobile_game_2048 tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 
  # Pods for mobile_game_2048 tvOS
 
end
